// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePgSslMode } from "./src/lib/pg-connection";

const databaseUrl = process.env["DATABASE_URL"]?.trim();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl ? normalizePgSslMode(databaseUrl) : databaseUrl,
  },
});
